title: 🌳 Links
baseline: Stay the owner of your links
description: Links is a Linktree clone powered by Cecil, Tailwind CSS and Font Awesome.
baseurl: https://links.cecil.app/
image: preview.png
theme:
  - applanding
  - netlify
applanding:
  buttons:
    - name: Netlify
      url: https://app.netlify.com/start/deploy?repository=https://github.com/Cecilapp/Links&stack=cms
      image: https://www.netlify.com/img/deploy/button.svg
  source: https://github.com/Cecilapp/Links
  documentation: https://github.com/Cecilapp/Links#readme
  screenshot:
    desktop: preview.png
    mobile: mobile-preview.png
  demo: https://cecil-links.netlify.app
#netlify:
#  redirects:
#    - from: https://cecil-links.netlify.app/*
#      to: https://links-demo.cecil.app/:splat
#      status: 301
#      force: true
